[package]
name = "curlyconf"
version = "0.1.0"
authors = ["Miquel van Smoorenburg <mikevs@xs4all.net>"]
edition = "2018"

[dependencies]
once_cell = "1.4.0"
regex = "1.3.9"
serde = { version = "1.0.114" }
